# Generated by Django 6.0.6 on 2026-06-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alphabet', '0001_initial'),
        ('audio_assets', '0001_initial'),
        ('learning', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('oral_intro_fr', models.CharField(blank=True, help_text='Ex: Écoute ce son, puis répète.', max_length=255)),
                ('oral_intro_en', models.CharField(blank=True, max_length=255)),
                ('oral_intro_ar', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('estimated_minutes', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningunit')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['unit', 'order_index', 'title_fr'],
            },
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('character', 'Character'), ('word', 'Word'), ('audio_only', 'Audio only'), ('image_only', 'Image only'), ('practice', 'Practice'), ('explanation', 'Explanation')], default='character', max_length=30)),
                ('title_fr', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('oral_prompt_fr', models.CharField(blank=True, help_text='Ex: Écoute et répète deux fois.', max_length=255)),
                ('oral_prompt_en', models.CharField(blank=True, max_length=255)),
                ('oral_prompt_ar', models.CharField(blank=True, max_length=255)),
                ('explanation_fr', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_ar', models.TextField(blank=True)),
                ('writing_hint_fr', models.TextField(blank=True)),
                ('writing_hint_en', models.TextField(blank=True)),
                ('writing_hint_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/items/images/')),
                ('repeat_count', models.PositiveIntegerField(default=2, help_text='Nombre de répétitions conseillé pour l’approche oral-first.')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_items', to='alphabet.character')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lessons.lesson')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_items', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'Lesson Item',
                'verbose_name_plural': 'Lesson Items',
                'ordering': ['lesson', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonItemAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('normal', 'Normal content audio'), ('slow', 'Slow content audio'), ('prompt', 'Oral instruction'), ('explanation', 'Explanation')], default='normal', max_length=40)),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_item_links', to='audio_assets.audioasset')),
                ('lesson_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='lessons.lessonitem')),
            ],
            options={
                'ordering': ['lesson_item', 'role', '-is_primary', 'order'],
                'constraints': [models.UniqueConstraint(fields=('lesson_item', 'audio_asset', 'role'), name='unique_lesson_item_audio_role')],
            },
        ),
    ]
