# Generated by Django 6.0.6 on 2026-06-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alphabet', '0001_initial'),
        ('audio_assets', '0001_initial'),
        ('learning', '0001_initial'),
        ('lessons', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('audio_to_character', 'Audio to character'), ('character_to_audio', 'Character to audio'), ('audio_to_image', 'Audio to image'), ('image_to_audio', 'Image to audio'), ('listen_and_repeat', 'Listen and repeat'), ('guided_keyboard', 'Guided keyboard'), ('text_to_character', 'Text to character')], default='audio_to_character', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('prompt_fr', models.CharField(blank=True, help_text='Instruction visible. Ex: Écoute et choisis le bon caractère.', max_length=255)),
                ('prompt_en', models.CharField(blank=True, max_length=255)),
                ('prompt_ar', models.CharField(blank=True, max_length=255)),
                ('oral_prompt_fr', models.CharField(blank=True, help_text='Instruction destinée à être lue ou jouée en audio.', max_length=255)),
                ('oral_prompt_en', models.CharField(blank=True, max_length=255)),
                ('oral_prompt_ar', models.CharField(blank=True, max_length=255)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='quizzes/questions/images/')),
                ('correct_text_answer', models.CharField(blank=True, help_text='Pour guided_keyboard ou réponse textuelle.', max_length=255)),
                ('explanation_fr', models.TextField(blank=True)),
                ('explanation_en', models.TextField(blank=True)),
                ('explanation_ar', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('min_options_required', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='alphabet.character')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='lessons.lesson')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learning.learningunit')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['difficulty', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_fr', models.CharField(blank=True, max_length=255)),
                ('text_en', models.CharField(blank=True, max_length=255)),
                ('text_ar', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quizzes/options/images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_options', to='alphabet.character')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_options', to='vocabulary.word')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Option',
                'verbose_name_plural': 'Quiz Options',
                'ordering': ['question', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('question', 'Question audio'), ('slow_question', 'Slow question audio'), ('explanation', 'Explanation audio'), ('correction', 'Correction audio')], default='question', max_length=40)),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_links', to='audio_assets.audioasset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='quizzes.quizquestion')),
            ],
            options={
                'ordering': ['question', 'role', '-is_primary', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['question_type'], name='quizzes_qui_questio_fdc69e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['difficulty'], name='quizzes_qui_difficu_a6ab79_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['status'], name='quizzes_qui_status_6d8c71_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizquestionaudio',
            constraint=models.UniqueConstraint(fields=('question', 'audio_asset', 'role'), name='unique_quiz_question_audio_role'),
        ),
    ]
