# Generated by Django 6.0.6 on 2026-06-07 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alphabet', '0001_initial'),
        ('learning', '0001_initial'),
        ('lessons', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('pack_type', models.CharField(choices=[('light', 'Light - text + essential audio'), ('normal', 'Normal - audio + images'), ('complete', 'Complete - all available media')], default='normal', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, null=True, upload_to='offline_packs/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_mb', models.FloatField(default=0)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='offline_packs', to='alphabet.character')),
                ('lessons', models.ManyToManyField(blank=True, related_name='offline_packs', to='lessons.lesson')),
                ('quiz_questions', models.ManyToManyField(blank=True, related_name='offline_packs', to='quizzes.quizquestion')),
                ('themes', models.ManyToManyField(blank=True, related_name='offline_packs', to='learning.learningtheme')),
                ('units', models.ManyToManyField(blank=True, related_name='offline_packs', to='learning.learningunit')),
                ('words', models.ManyToManyField(blank=True, related_name='offline_packs', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'Lesson Pack',
                'verbose_name_plural': 'Lesson Packs',
                'ordering': ['level', 'title_fr', 'version'],
            },
        ),
    ]
