# Generated by Django 6.0.6 on 2026-06-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Caractère Beriya Erfe.', max_length=10, unique=True)),
                ('unicode_code', models.CharField(help_text='Exemple : U+16EA0.', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('name_fr', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('latin_transcription', models.CharField(blank=True, max_length=120)),
                ('arabic_transcription', models.CharField(blank=True, max_length=120)),
                ('character_type', models.CharField(choices=[('vowel', 'Vowel'), ('consonant', 'Consonant'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['order_index', 'unicode_code'],
            },
        ),
        migrations.CreateModel(
            name='CharacterAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('normal', 'Normal pronunciation'), ('slow', 'Slow pronunciation'), ('example', 'Example pronunciation')], default='normal', max_length=30)),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='audio_assets.audioasset')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='alphabet.character')),
            ],
            options={
                'ordering': ['character', 'role', '-is_primary', 'order'],
                'constraints': [models.UniqueConstraint(fields=('character', 'audio_asset', 'role'), name='unique_character_audio_role')],
            },
        ),
    ]
