# Generated by Django 6.0.6 on 2026-06-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alphabet', '0001_initial'),
        ('audio_assets', '0001_initial'),
        ('learning', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoEnaPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('beriya_title', models.CharField(blank=True, help_text='Titre éventuel en Beriya Erfe.', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('caption_fr', models.TextField(blank=True)),
                ('caption_en', models.TextField(blank=True)),
                ('caption_ar', models.TextField(blank=True)),
                ('beriya_caption', models.TextField(blank=True, help_text='Description éventuelle en Beriya Erfe.')),
                ('publication_type', models.CharField(choices=[('short_video', 'Short video'), ('image', 'Image'), ('audio_story', 'Audio story'), ('proverb', 'Proverb'), ('writing_demo', 'Writing demonstration'), ('culture_note', 'Culture note')], default='image', max_length=40)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='no_ena/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='no_ena/thumbnails/')),
                ('video_file', models.FileField(blank=True, help_text='Vidéo courte MP4 optimisée mobile.', null=True, upload_to='no_ena/videos/')),
                ('contributor_name', models.CharField(blank=True, max_length=150)),
                ('culture_theme', models.CharField(blank=True, help_text='Exemple : proverbes, écriture, famille, tradition, histoire.', max_length=150)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('available_offline', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_ena_contributions', to=settings.AUTH_USER_MODEL)),
                ('primary_audio_asset', models.ForeignKey(blank=True, help_text='Audio principal : narration, proverbe, explication, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_ena_publications', to='audio_assets.audioasset')),
                ('related_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_ena_publications', to='alphabet.character')),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_ena_publications', to='learning.learningunit')),
                ('related_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_ena_publications', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'No Ena Publication',
                'verbose_name_plural': 'No Ena Publications',
                'ordering': ['-is_featured', 'order_index', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['publication_type'], name='no_ena_noen_publica_da7b3f_idx'), models.Index(fields=['status'], name='no_ena_noen_status_746129_idx'), models.Index(fields=['is_featured'], name='no_ena_noen_is_feat_79b021_idx'), models.Index(fields=['available_offline'], name='no_ena_noen_availab_23005a_idx')],
            },
        ),
    ]
