# Generated by Django 6.0.6 on 2026-06-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alphabet', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='learning/themes/covers/')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Theme',
                'verbose_name_plural': 'Learning Themes',
                'ordering': ['level', 'order_index', 'title_fr'],
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('min_score_to_pass', models.PositiveIntegerField(default=70, help_text='Score minimum en pourcentage pour valider l’unité.')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='learning_units', to='alphabet.character')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.learningtheme')),
                ('words', models.ManyToManyField(blank=True, related_name='learning_units', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'Learning Unit',
                'verbose_name_plural': 'Learning Units',
                'ordering': ['theme', 'order_index', 'title_fr'],
            },
        ),
    ]
