# Generated by Django 6.0.6 on 2026-06-07 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Identifiant local stable pour utilisateur sans compte.', max_length=120)),
                ('status', models.CharField(choices=[('started', 'Started'), ('review', 'Review'), ('completed', 'Completed')], default='started', max_length=30)),
                ('last_stage', models.CharField(default='intro', help_text='intro, lessons, characters, words, quiz, result', max_length=50)),
                ('lessons_seen', models.PositiveIntegerField(default=0)),
                ('characters_seen', models.PositiveIntegerField(default=0)),
                ('words_seen', models.PositiveIntegerField(default=0)),
                ('quizzes_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('best_score_percent', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.learningunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-client_updated_at', '-synced_at'],
                'indexes': [models.Index(fields=['device_id'], name='progress_un_device__35a60a_idx'), models.Index(fields=['status'], name='progress_un_status_1030f3_idx'), models.Index(fields=['completed'], name='progress_un_complet_c50f18_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'unit'), name='unique_device_unit_progress')],
            },
        ),
    ]
