# Generated by Django 6.0.6 on 2026-06-07 05:30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Nom interne de l’audio.', max_length=255)),
                ('file', models.FileField(help_text='Formats acceptés : MP3, M4A, WAV.', upload_to='audio_assets/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'wav'])])),
                ('audio_type', models.CharField(choices=[('character', 'Character'), ('phoneme', 'Phoneme'), ('syllable', 'Syllable'), ('word', 'Word'), ('sentence', 'Sentence'), ('proverb', 'Proverb'), ('story', 'Story'), ('lesson_prompt', 'Lesson prompt'), ('quiz_prompt', 'Quiz prompt'), ('quiz_explanation', 'Quiz explanation'), ('feedback', 'Feedback'), ('no_ena', 'No Ena')], max_length=40)),
                ('speed', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('speaker_name', models.CharField(blank=True, max_length=150)),
                ('speaker_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('dialect_region', models.CharField(blank=True, help_text='Exemple : Borkou, Ennedi, Darfour, diaspora, etc.', max_length=150)),
                ('mime_type', models.CharField(blank=True, help_text='Exemple : audio/mpeg, audio/mp4, audio/wav.', max_length=100)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, help_text='Texte ou transcription correspondant à l’audio.')),
                ('recording_quality', models.CharField(blank=True, help_text='Exemple : draft, acceptable, studio, verified.', max_length=50)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('available_offline', models.BooleanField(default=True, help_text='Peut être inclus dans les packs offline.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Asset',
                'verbose_name_plural': 'Audio Assets',
                'ordering': ['audio_type', 'title', '-created_at'],
            },
        ),
    ]
