# Generated by Django 6.0.6 on 2026-06-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Word Category',
                'verbose_name_plural': 'Word Categories',
                'ordering': ['order_index', 'name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beriya_text', models.CharField(help_text='Mot en Beriya Erfe.', max_length=255)),
                ('latin_transcription', models.CharField(blank=True, max_length=255)),
                ('arabic_transcription', models.CharField(blank=True, max_length=255)),
                ('french_translation', models.CharField(blank=True, max_length=255)),
                ('english_translation', models.CharField(blank=True, max_length=255)),
                ('arabic_translation', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=30)),
                ('difficulty_order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/images/')),
                ('oral_prompt', models.CharField(blank=True, help_text='Instruction courte audio-first.', max_length=255)),
                ('pronunciation_note', models.TextField(blank=True)),
                ('dialect_note', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('validated', 'Validated'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('available_offline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='vocabulary.wordcategory')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['difficulty_order', 'beriya_text'],
            },
        ),
        migrations.CreateModel(
            name='WordAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('normal', 'Normal pronunciation'), ('slow', 'Slow pronunciation'), ('example', 'Example sentence'), ('syllable_breakdown', 'Syllable breakdown')], default='normal', max_length=40)),
                ('is_primary', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('audio_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='audio_assets.audioasset')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='vocabulary.word')),
            ],
            options={
                'ordering': ['word', 'role', '-is_primary', 'order'],
                'constraints': [models.UniqueConstraint(fields=('word', 'audio_asset', 'role'), name='unique_word_audio_role')],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['beriya_text'], name='vocabulary__beriya__884823_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['difficulty'], name='vocabulary__difficu_f47f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['validation_status'], name='vocabulary__validat_fef491_idx'),
        ),
    ]
