# Generated by Django 6.0.6 on 2026-06-07 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Identifiant local stable pour feedback sans compte.', max_length=120)),
                ('feedback_type', models.CharField(choices=[('pronunciation', 'Pronunciation problem'), ('translation', 'Translation problem'), ('audio_quality', 'Audio quality problem'), ('wrong_character', 'Wrong character'), ('wrong_word', 'Wrong word'), ('wrong_image', 'Wrong image'), ('technical', 'Technical problem'), ('content_suggestion', 'Content suggestion'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, help_text='Description du problème ou de la suggestion.')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/screenshots/')),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, help_text='android, ios, web, etc.', max_length=50)),
                ('language_code', models.CharField(blank=True, help_text='fr, en, ar, etc.', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('fixed', 'Fixed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_feedback', models.ForeignKey(blank=True, help_text='Feedback vocal envoyé ou ajouté par un utilisateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to='audio_assets.audioasset')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id'], name='feedback_fe_device__6dd9b4_idx'), models.Index(fields=['feedback_type'], name='feedback_fe_feedbac_a6fd99_idx'), models.Index(fields=['status'], name='feedback_fe_status_5f403f_idx'), models.Index(fields=['priority'], name='feedback_fe_priorit_8fd080_idx')],
            },
        ),
    ]
